---
# Variables for misc-packages role

macos_brew_taps:
  - warrensbox/tap

macos_brew_packages:
  - diceware
  - httpie
  - jq
  - kubectx
  - pyenv
  - rsync
  - tree
  - yq
  - zip
  - warrensbox/tap/tfswitch

macos_brew_casks:
  - ghostty
  - raycast
  - rectangle
